"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import Sidebar from "../components/Sidebar";
import ProductPicker from "../components/ProductPicker";
type Location={id:string;name:string;code:string};type Line={productId:string;productName:string;quantity:string;unitPrice:string;locationId:string};
export default function SalesPage(){
 const [storeName,setStoreName]=useState("");const [registerName,setRegisterName]=useState("");const [cashierName,setCashierName]=useState("");const [currency]=useState("KES");const [locations,setLocations]=useState<Location[]>([]);const [lines,setLines]=useState<Line[]>([{productId:"",productName:"",quantity:"1",unitPrice:"",locationId:""}]);const [method,setMethod]=useState("CASH");const [paymentAmount,setPaymentAmount]=useState("");const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{fetch("/api/inventory/locations").then(r=>r.ok?r.json():[]).then(setLocations).catch(()=>setLocations([]))},[]);
 const total=useMemo(()=>lines.reduce((n,l)=>n+(Number(l.quantity)||0)*(Number(l.unitPrice)||0),0),[lines]);
 async function submit(e:FormEvent){e.preventDefault();setError("");setMessage("");if(!storeName.trim()||!registerName.trim()||!cashierName.trim())return setError("Enter the store, register, and cashier names.");if(lines.some(l=>!l.productId||!Number.isSafeInteger(Number(l.quantity))||Number(l.quantity)<1||!Number.isSafeInteger(Number(l.unitPrice))||Number(l.unitPrice)<0||!l.locationId))return setError("Choose a product and location and enter whole-number quantity and KES price values.");if(!Number.isSafeInteger(Number(paymentAmount))||Number(paymentAmount)!==total)return setError("Tender amount must be a whole KES amount equal to the sale total.");setBusy(true);try{const response=await fetch("/api/sales",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({storeName:storeName.trim(),registerName:registerName.trim(),cashierName:cashierName.trim(),currency,items:lines.map(l=>({productId:l.productId,quantity:Number(l.quantity),unitPrice:Number(l.unitPrice),locationId:l.locationId})),payments:[{method,amount:Number(paymentAmount)}]})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Sale could not be completed");setMessage(`Sale recorded: ${currency} ${total.toLocaleString("en-KE")} · ${data.eventStatus||"event queued"}`);setLines([{productId:"",productName:"",quantity:"1",unitPrice:"",locationId:""}]);setPaymentAmount("")}catch(e){setError(e instanceof Error?e.message:"Sale failed")}finally{setBusy(false)}}
 return <div className="flex min-h-screen bg-slate-50"><Sidebar/><main className="mx-auto w-full max-w-6xl space-y-6 p-6"><header><p className="text-sm font-semibold text-blue-600">Storefront</p><h1 className="text-3xl font-bold">Retail Sales</h1><p className="mt-2 text-slate-500">Select products by name, validate available inventory, and record the tender.</p></header>{error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-emerald-700">{message}</p>}<form onSubmit={submit} className="space-y-6 rounded-2xl border bg-white p-6"><div className="grid gap-4 md:grid-cols-3">{[
  {label:"Store name",value:storeName,setter:setStoreName},
  {label:"Register name",value:registerName,setter:setRegisterName},
  {label:"Cashier name",value:cashierName,setter:setCashierName}
].map(({label,value,setter})=><label key={label} className="space-y-1 text-sm font-medium">{label}<input required value={value} onChange={e=>setter(e.target.value)} className="w-full rounded-lg border px-3 py-2" placeholder={`Enter ${label.toLowerCase()}`}/></label>)}</div><section className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-semibold">Items</h2><button type="button" onClick={()=>setLines([...lines,{productId:"",productName:"",quantity:"1",unitPrice:"",locationId:""}])} className="rounded-lg border px-3 py-2 text-sm">Add item</button></div>{lines.map((line,index)=><div key={index} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[2fr_1.5fr_100px_150px_130px_auto]"><ProductPicker value={line.productId} onChange={id=>setLines(lines.map((x,i)=>i===index?{...x,productId:id}:x))} onProduct={product=>setLines(lines.map((x,i)=>i===index?{...x,productName:product?.productName||""}:x))}/><select required value={line.locationId} onChange={e=>setLines(lines.map((x,i)=>i===index?{...x,locationId:e.target.value}:x))} className="rounded-lg border px-3 py-2"><option value="">Stock location</option>{locations.map(l=><option value={l.id} key={l.id}>{l.name} · {l.code}</option>)}</select><input aria-label="Quantity" type="number" min="1" step="1" inputMode="numeric" required value={line.quantity} onChange={e=>setLines(lines.map((x,i)=>i===index?{...x,quantity:e.target.value}:x))} className="rounded-lg border px-3 py-2"/><input aria-label="Unit price in KES" type="number" min="0" step="1" inputMode="numeric" required placeholder="Price KES" value={line.unitPrice} onChange={e=>setLines(lines.map((x,i)=>i===index?{...x,unitPrice:e.target.value}:x))} className="rounded-lg border px-3 py-2"/><p className="self-center text-sm font-semibold">{line.productName}</p>{lines.length>1&&<button type="button" aria-label="Remove item" onClick={()=>setLines(lines.filter((_,i)=>i!==index))} className="text-red-600">Remove</button>}</div>)}</section><div className="grid gap-4 border-t pt-5 sm:grid-cols-3"><div><label className="mb-1 block text-sm font-medium">Tender method</label><select value={method} onChange={e=>setMethod(e.target.value)} className="w-full rounded-lg border px-3 py-2"><option value="CASH">Cash</option><option value="CARD">Card</option><option value="GIFT_CARD">Gift card</option></select></div><label className="space-y-1 text-sm font-medium">Amount tendered (KES)<input type="number" min="0" step="1" inputMode="numeric" required value={paymentAmount} onChange={e=>setPaymentAmount(e.target.value)} className="w-full rounded-lg border px-3 py-2"/></label><div className="self-end text-xl font-bold">Total: KES {total.toLocaleString("en-KE")}</div></div><button disabled={busy} className="rounded-lg bg-blue-600 px-5 py-3 font-semibold text-white disabled:opacity-50">{busy?"Processing…":"Complete sale"}</button></form></main></div>
}
