"use client";
import { useEffect, useState } from "react";
type Product = { productId: string; productName: string; unitCost: number };
export default function ProductPicker({ value, onChange, onProduct, allowedIds }: { value: string; onChange: (id: string) => void; onProduct?: (product: Product | null) => void; allowedIds?: string[] }) {
  const [term,setTerm]=useState(""); const [results,setResults]=useState<Product[]>([]); const [open,setOpen]=useState(false); const [loading,setLoading]=useState(false);
  useEffect(()=>{let active=true; if(value){fetch(`/api/inventory/products?ids=${encodeURIComponent(value)}`).then(r=>r.ok?r.json():[]).then((rows:Product[])=>{if(active&&rows[0])setTerm(rows[0].productName)}).catch(()=>{});} return ()=>{active=false}},[value]);
  useEffect(()=>{let active=true; const timer=setTimeout(async()=>{if(!open)return;if(allowedIds && allowedIds.length===0){setResults([]);setLoading(false);return;}setLoading(true);try{const query = allowedIds ? `ids=${encodeURIComponent(allowedIds.join(","))}` : `search=${encodeURIComponent(term)}&limit=20`;const r=await fetch(`/api/inventory/products?${query}`);const rows:Product[]=r.ok?await r.json():[];if(active)setResults(allowedIds?.length?rows.filter(p=>p.productName.toLowerCase().includes(term.toLowerCase())):rows)}catch{if(active)setResults([])}finally{if(active)setLoading(false)}},180);return()=>{active=false;clearTimeout(timer)}},[term,open,allowedIds]);
  return <div className="relative"><label className="sr-only">Search products by name</label><input type="search" value={term} onFocus={()=>setOpen(true)} onBlur={()=>setTimeout(()=>setOpen(false),120)} onChange={e=>{setTerm(e.target.value);onChange("");onProduct?.(null);setOpen(true)}} placeholder="Search products by name…" autoComplete="off" className="w-full rounded-lg border border-slate-300 bg-white px-3 py-2.5 text-sm" aria-expanded={open} />{open&&(term.length>0||results.length>0)&&<ul className="absolute z-30 mt-1 max-h-56 w-full overflow-auto rounded-lg border border-slate-200 bg-white shadow-lg">{loading&&<li className="px-3 py-2 text-sm text-slate-500">Searching…</li>}{!loading&&results.length===0&&<li className="px-3 py-2 text-sm text-slate-500">No matching products</li>}{results.map(p=><li key={p.productId}><button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>{setTerm(p.productName);onChange(p.productId);onProduct?.(p);setOpen(false)}} className="w-full px-3 py-2 text-left text-sm hover:bg-blue-50"><span className="block font-medium">{p.productName}</span><span className="text-xs text-slate-500">Cost {p.unitCost.toLocaleString()}</span></button></li>)}</ul>}<input type="hidden" value={value} /></div>;
}
